// <auto-generated />
using Ilvbu.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ilvbu.DataBase.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20190613075737_InitModel")]
    partial class InitModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ilvbu.DataBase.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .HasMaxLength(128);

                    b.Property<string>("UserName")
                        .HasMaxLength(128);

                    b.Property<string>("WechatID")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("Ilvbu.DataBase.Models.WxLoginRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ExpiresIn")
                        .HasMaxLength(64);

                    b.Property<string>("Guid")
                        .HasMaxLength(128);

                    b.Property<string>("OpenId")
                        .HasMaxLength(64);

                    b.Property<string>("SessionKey")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("WxLoginRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
